version: '3.8'

services:
  react-messenger:
    container_name: frontend-app
    build:
      context: .
      dockerfile: apps/react-messenger/Dockerfile
    ports:
      - '3000:80' # Expose the UI app on port 3000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: backend-app
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '4000:3000' # Expose the backend on port 4000
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: messenger
      JWT_SECRET: your-secret-key

  db:
    container_name: postgres-db
    image: postgres:14
    ports:
      - '5432:5432' # Expose the database on port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messenger
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
